/*
OpenAPI UniBee

This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unibee

import (
	"encoding/json"
)

// checks if the UnibeeInternalLogicGatewayRoUserAccountSimplify type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnibeeInternalLogicGatewayRoUserAccountSimplify{}

// UnibeeInternalLogicGatewayRoUserAccountSimplify struct for UnibeeInternalLogicGatewayRoUserAccountSimplify
type UnibeeInternalLogicGatewayRoUserAccountSimplify struct {
	// address
	Address *string `json:"address,omitempty"`
	// create utc time
	CreateTime *int64 `json:"createTime,omitempty"`
	// email
	Email *string `json:"email,omitempty"`
	// externalUserId
	ExternalUserId *string `json:"externalUserId,omitempty"`
	// first name
	FirstName *string `json:"firstName,omitempty"`
	// userId
	Id *int64 `json:"id,omitempty"`
	// last name
	LastName *string `json:"lastName,omitempty"`
	// merchant id
	MerchantId *int64 `json:"merchantId,omitempty"`
}

// NewUnibeeInternalLogicGatewayRoUserAccountSimplify instantiates a new UnibeeInternalLogicGatewayRoUserAccountSimplify object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnibeeInternalLogicGatewayRoUserAccountSimplify() *UnibeeInternalLogicGatewayRoUserAccountSimplify {
	this := UnibeeInternalLogicGatewayRoUserAccountSimplify{}
	return &this
}

// NewUnibeeInternalLogicGatewayRoUserAccountSimplifyWithDefaults instantiates a new UnibeeInternalLogicGatewayRoUserAccountSimplify object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnibeeInternalLogicGatewayRoUserAccountSimplifyWithDefaults() *UnibeeInternalLogicGatewayRoUserAccountSimplify {
	this := UnibeeInternalLogicGatewayRoUserAccountSimplify{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) SetAddress(v string) {
	o.Address = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetCreateTime() int64 {
	if o == nil || IsNil(o.CreateTime) {
		var ret int64
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetCreateTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given int64 and assigns it to the CreateTime field.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) SetCreateTime(v int64) {
	o.CreateTime = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) SetEmail(v string) {
	o.Email = &v
}

// GetExternalUserId returns the ExternalUserId field value if set, zero value otherwise.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetExternalUserId() string {
	if o == nil || IsNil(o.ExternalUserId) {
		var ret string
		return ret
	}
	return *o.ExternalUserId
}

// GetExternalUserIdOk returns a tuple with the ExternalUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetExternalUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalUserId) {
		return nil, false
	}
	return o.ExternalUserId, true
}

// HasExternalUserId returns a boolean if a field has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) HasExternalUserId() bool {
	if o != nil && !IsNil(o.ExternalUserId) {
		return true
	}

	return false
}

// SetExternalUserId gets a reference to the given string and assigns it to the ExternalUserId field.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) SetExternalUserId(v string) {
	o.ExternalUserId = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) SetFirstName(v string) {
	o.FirstName = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) SetId(v int64) {
	o.Id = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) SetLastName(v string) {
	o.LastName = &v
}

// GetMerchantId returns the MerchantId field value if set, zero value otherwise.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetMerchantId() int64 {
	if o == nil || IsNil(o.MerchantId) {
		var ret int64
		return ret
	}
	return *o.MerchantId
}

// GetMerchantIdOk returns a tuple with the MerchantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) GetMerchantIdOk() (*int64, bool) {
	if o == nil || IsNil(o.MerchantId) {
		return nil, false
	}
	return o.MerchantId, true
}

// HasMerchantId returns a boolean if a field has been set.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) HasMerchantId() bool {
	if o != nil && !IsNil(o.MerchantId) {
		return true
	}

	return false
}

// SetMerchantId gets a reference to the given int64 and assigns it to the MerchantId field.
func (o *UnibeeInternalLogicGatewayRoUserAccountSimplify) SetMerchantId(v int64) {
	o.MerchantId = &v
}

func (o UnibeeInternalLogicGatewayRoUserAccountSimplify) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnibeeInternalLogicGatewayRoUserAccountSimplify) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.CreateTime) {
		toSerialize["createTime"] = o.CreateTime
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.ExternalUserId) {
		toSerialize["externalUserId"] = o.ExternalUserId
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.MerchantId) {
		toSerialize["merchantId"] = o.MerchantId
	}
	return toSerialize, nil
}

type NullableUnibeeInternalLogicGatewayRoUserAccountSimplify struct {
	value *UnibeeInternalLogicGatewayRoUserAccountSimplify
	isSet bool
}

func (v NullableUnibeeInternalLogicGatewayRoUserAccountSimplify) Get() *UnibeeInternalLogicGatewayRoUserAccountSimplify {
	return v.value
}

func (v *NullableUnibeeInternalLogicGatewayRoUserAccountSimplify) Set(val *UnibeeInternalLogicGatewayRoUserAccountSimplify) {
	v.value = val
	v.isSet = true
}

func (v NullableUnibeeInternalLogicGatewayRoUserAccountSimplify) IsSet() bool {
	return v.isSet
}

func (v *NullableUnibeeInternalLogicGatewayRoUserAccountSimplify) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnibeeInternalLogicGatewayRoUserAccountSimplify(val *UnibeeInternalLogicGatewayRoUserAccountSimplify) *NullableUnibeeInternalLogicGatewayRoUserAccountSimplify {
	return &NullableUnibeeInternalLogicGatewayRoUserAccountSimplify{value: val, isSet: true}
}

func (v NullableUnibeeInternalLogicGatewayRoUserAccountSimplify) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnibeeInternalLogicGatewayRoUserAccountSimplify) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


