/*
OpenAPI UniBee

UniBee Api Server

API version: daily,buildtime:202512220824
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unibee

import (
	"encoding/json"
)

// checks if the UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes{}

// UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes struct for UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes
type UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes struct {
	// Operation result message
	Message *string `json:"message,omitempty"`
	// Whether the operation was successful
	Success *bool `json:"success,omitempty"`
}

// NewUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes instantiates a new UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes() *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes {
	this := UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes{}
	return &this
}

// NewUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessResWithDefaults instantiates a new UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessResWithDefaults() *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes {
	this := UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) SetMessage(v string) {
	o.Message = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) SetSuccess(v bool) {
	o.Success = &v
}

func (o UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes struct {
	value *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes
	isSet bool
}

func (v NullableUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) Get() *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes {
	return v.value
}

func (v *NullableUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) Set(val *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) {
	v.value = val
	v.isSet = true
}

func (v NullableUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) IsSet() bool {
	return v.isSet
}

func (v *NullableUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes(val *UnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) *NullableUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes {
	return &NullableUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes{value: val, isSet: true}
}

func (v NullableUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnibeeApiSystemSubscriptionManualTriggerPendingUpdatePaymentSuccessRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


