/*
OpenAPI UniBee

UniBee Api Server

API version: daily,buildtime:202504011414
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unibee

import (
	"encoding/json"
)

// checks if the UnibeeApiMerchantMemberUpdateReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnibeeApiMerchantMemberUpdateReq{}

// UnibeeApiMerchantMemberUpdateReq struct for UnibeeApiMerchantMemberUpdateReq
type UnibeeApiMerchantMemberUpdateReq struct {
	// The firstName of member
	FirstName *string `json:"firstName,omitempty"`
	// The lastName of member
	LastName *string `json:"lastName,omitempty"`
	// mobile
	Mobile *string `json:"mobile,omitempty"`
}

// NewUnibeeApiMerchantMemberUpdateReq instantiates a new UnibeeApiMerchantMemberUpdateReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnibeeApiMerchantMemberUpdateReq() *UnibeeApiMerchantMemberUpdateReq {
	this := UnibeeApiMerchantMemberUpdateReq{}
	return &this
}

// NewUnibeeApiMerchantMemberUpdateReqWithDefaults instantiates a new UnibeeApiMerchantMemberUpdateReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnibeeApiMerchantMemberUpdateReqWithDefaults() *UnibeeApiMerchantMemberUpdateReq {
	this := UnibeeApiMerchantMemberUpdateReq{}
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UnibeeApiMerchantMemberUpdateReq) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantMemberUpdateReq) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UnibeeApiMerchantMemberUpdateReq) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UnibeeApiMerchantMemberUpdateReq) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UnibeeApiMerchantMemberUpdateReq) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantMemberUpdateReq) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UnibeeApiMerchantMemberUpdateReq) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UnibeeApiMerchantMemberUpdateReq) SetLastName(v string) {
	o.LastName = &v
}

// GetMobile returns the Mobile field value if set, zero value otherwise.
func (o *UnibeeApiMerchantMemberUpdateReq) GetMobile() string {
	if o == nil || IsNil(o.Mobile) {
		var ret string
		return ret
	}
	return *o.Mobile
}

// GetMobileOk returns a tuple with the Mobile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantMemberUpdateReq) GetMobileOk() (*string, bool) {
	if o == nil || IsNil(o.Mobile) {
		return nil, false
	}
	return o.Mobile, true
}

// HasMobile returns a boolean if a field has been set.
func (o *UnibeeApiMerchantMemberUpdateReq) HasMobile() bool {
	if o != nil && !IsNil(o.Mobile) {
		return true
	}

	return false
}

// SetMobile gets a reference to the given string and assigns it to the Mobile field.
func (o *UnibeeApiMerchantMemberUpdateReq) SetMobile(v string) {
	o.Mobile = &v
}

func (o UnibeeApiMerchantMemberUpdateReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnibeeApiMerchantMemberUpdateReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.Mobile) {
		toSerialize["mobile"] = o.Mobile
	}
	return toSerialize, nil
}

type NullableUnibeeApiMerchantMemberUpdateReq struct {
	value *UnibeeApiMerchantMemberUpdateReq
	isSet bool
}

func (v NullableUnibeeApiMerchantMemberUpdateReq) Get() *UnibeeApiMerchantMemberUpdateReq {
	return v.value
}

func (v *NullableUnibeeApiMerchantMemberUpdateReq) Set(val *UnibeeApiMerchantMemberUpdateReq) {
	v.value = val
	v.isSet = true
}

func (v NullableUnibeeApiMerchantMemberUpdateReq) IsSet() bool {
	return v.isSet
}

func (v *NullableUnibeeApiMerchantMemberUpdateReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnibeeApiMerchantMemberUpdateReq(val *UnibeeApiMerchantMemberUpdateReq) *NullableUnibeeApiMerchantMemberUpdateReq {
	return &NullableUnibeeApiMerchantMemberUpdateReq{value: val, isSet: true}
}

func (v NullableUnibeeApiMerchantMemberUpdateReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnibeeApiMerchantMemberUpdateReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


