/*
OpenAPI UniBee

UniBee Api Server

API version: daily,buildtime:202601040317
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unibee

import (
	"encoding/json"
)

// checks if the MerchantWebhookWebhookZapierConnectUrlPost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantWebhookWebhookZapierConnectUrlPost200ResponseData{}

// MerchantWebhookWebhookZapierConnectUrlPost200ResponseData struct for MerchantWebhookWebhookZapierConnectUrlPost200ResponseData
type MerchantWebhookWebhookZapierConnectUrlPost200ResponseData struct {
	// Zapier Connect Url
	ZapierConnectUrl *string `json:"zapierConnectUrl,omitempty"`
}

// NewMerchantWebhookWebhookZapierConnectUrlPost200ResponseData instantiates a new MerchantWebhookWebhookZapierConnectUrlPost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantWebhookWebhookZapierConnectUrlPost200ResponseData() *MerchantWebhookWebhookZapierConnectUrlPost200ResponseData {
	this := MerchantWebhookWebhookZapierConnectUrlPost200ResponseData{}
	return &this
}

// NewMerchantWebhookWebhookZapierConnectUrlPost200ResponseDataWithDefaults instantiates a new MerchantWebhookWebhookZapierConnectUrlPost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantWebhookWebhookZapierConnectUrlPost200ResponseDataWithDefaults() *MerchantWebhookWebhookZapierConnectUrlPost200ResponseData {
	this := MerchantWebhookWebhookZapierConnectUrlPost200ResponseData{}
	return &this
}

// GetZapierConnectUrl returns the ZapierConnectUrl field value if set, zero value otherwise.
func (o *MerchantWebhookWebhookZapierConnectUrlPost200ResponseData) GetZapierConnectUrl() string {
	if o == nil || IsNil(o.ZapierConnectUrl) {
		var ret string
		return ret
	}
	return *o.ZapierConnectUrl
}

// GetZapierConnectUrlOk returns a tuple with the ZapierConnectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantWebhookWebhookZapierConnectUrlPost200ResponseData) GetZapierConnectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ZapierConnectUrl) {
		return nil, false
	}
	return o.ZapierConnectUrl, true
}

// HasZapierConnectUrl returns a boolean if a field has been set.
func (o *MerchantWebhookWebhookZapierConnectUrlPost200ResponseData) HasZapierConnectUrl() bool {
	if o != nil && !IsNil(o.ZapierConnectUrl) {
		return true
	}

	return false
}

// SetZapierConnectUrl gets a reference to the given string and assigns it to the ZapierConnectUrl field.
func (o *MerchantWebhookWebhookZapierConnectUrlPost200ResponseData) SetZapierConnectUrl(v string) {
	o.ZapierConnectUrl = &v
}

func (o MerchantWebhookWebhookZapierConnectUrlPost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantWebhookWebhookZapierConnectUrlPost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ZapierConnectUrl) {
		toSerialize["zapierConnectUrl"] = o.ZapierConnectUrl
	}
	return toSerialize, nil
}

type NullableMerchantWebhookWebhookZapierConnectUrlPost200ResponseData struct {
	value *MerchantWebhookWebhookZapierConnectUrlPost200ResponseData
	isSet bool
}

func (v NullableMerchantWebhookWebhookZapierConnectUrlPost200ResponseData) Get() *MerchantWebhookWebhookZapierConnectUrlPost200ResponseData {
	return v.value
}

func (v *NullableMerchantWebhookWebhookZapierConnectUrlPost200ResponseData) Set(val *MerchantWebhookWebhookZapierConnectUrlPost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantWebhookWebhookZapierConnectUrlPost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantWebhookWebhookZapierConnectUrlPost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantWebhookWebhookZapierConnectUrlPost200ResponseData(val *MerchantWebhookWebhookZapierConnectUrlPost200ResponseData) *NullableMerchantWebhookWebhookZapierConnectUrlPost200ResponseData {
	return &NullableMerchantWebhookWebhookZapierConnectUrlPost200ResponseData{value: val, isSet: true}
}

func (v NullableMerchantWebhookWebhookZapierConnectUrlPost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantWebhookWebhookZapierConnectUrlPost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


