/*
OpenAPI UniBee

UniBee Api Server

API version: daily,buildtime:202603161017
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unibee

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq{}

// UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq Mark payment as failed using external gateway result. Auth: OpenAPI + signature (HMAC-SHA256, hex).
type UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq struct {
	// External payment transaction id from gateway, used for correlation
	ExternalTransactionId string `json:"externalTransactionId"`
	// Human-readable failure reason from external gateway
	FailureReason *string `json:"failureReason,omitempty"`
	// External gateway id (optional), if omitted will be resolved from paymentId
	GatewayId *int64 `json:"gatewayId,omitempty"`
	// The UniBee paymentId
	PaymentId string `json:"paymentId"`
	// HMAC-SHA256 hex signature using External Gateway API Key over 'paymentId|externalTransactionId|timestamp'
	Signature string `json:"signature"`
	// Unix timestamp in seconds, used for signature and anti-replay
	Timestamp int64 `json:"timestamp"`
}

type _UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq

// NewUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq instantiates a new UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq(externalTransactionId string, paymentId string, signature string, timestamp int64) *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq {
	this := UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq{}
	this.ExternalTransactionId = externalTransactionId
	this.PaymentId = paymentId
	this.Signature = signature
	this.Timestamp = timestamp
	return &this
}

// NewUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReqWithDefaults instantiates a new UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReqWithDefaults() *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq {
	this := UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq{}
	return &this
}

// GetExternalTransactionId returns the ExternalTransactionId field value
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetExternalTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalTransactionId
}

// GetExternalTransactionIdOk returns a tuple with the ExternalTransactionId field value
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetExternalTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalTransactionId, true
}

// SetExternalTransactionId sets field value
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) SetExternalTransactionId(v string) {
	o.ExternalTransactionId = v
}

// GetFailureReason returns the FailureReason field value if set, zero value otherwise.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetFailureReason() string {
	if o == nil || IsNil(o.FailureReason) {
		var ret string
		return ret
	}
	return *o.FailureReason
}

// GetFailureReasonOk returns a tuple with the FailureReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetFailureReasonOk() (*string, bool) {
	if o == nil || IsNil(o.FailureReason) {
		return nil, false
	}
	return o.FailureReason, true
}

// HasFailureReason returns a boolean if a field has been set.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) HasFailureReason() bool {
	if o != nil && !IsNil(o.FailureReason) {
		return true
	}

	return false
}

// SetFailureReason gets a reference to the given string and assigns it to the FailureReason field.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) SetFailureReason(v string) {
	o.FailureReason = &v
}

// GetGatewayId returns the GatewayId field value if set, zero value otherwise.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetGatewayId() int64 {
	if o == nil || IsNil(o.GatewayId) {
		var ret int64
		return ret
	}
	return *o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetGatewayIdOk() (*int64, bool) {
	if o == nil || IsNil(o.GatewayId) {
		return nil, false
	}
	return o.GatewayId, true
}

// HasGatewayId returns a boolean if a field has been set.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) HasGatewayId() bool {
	if o != nil && !IsNil(o.GatewayId) {
		return true
	}

	return false
}

// SetGatewayId gets a reference to the given int64 and assigns it to the GatewayId field.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) SetGatewayId(v int64) {
	o.GatewayId = &v
}

// GetPaymentId returns the PaymentId field value
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetPaymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetPaymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentId, true
}

// SetPaymentId sets field value
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) SetPaymentId(v string) {
	o.PaymentId = v
}

// GetSignature returns the Signature field value
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) SetSignature(v string) {
	o.Signature = v
}

// GetTimestamp returns the Timestamp field value
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetTimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) GetTimestampOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) SetTimestamp(v int64) {
	o.Timestamp = v
}

func (o UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["externalTransactionId"] = o.ExternalTransactionId
	if !IsNil(o.FailureReason) {
		toSerialize["failureReason"] = o.FailureReason
	}
	if !IsNil(o.GatewayId) {
		toSerialize["gatewayId"] = o.GatewayId
	}
	toSerialize["paymentId"] = o.PaymentId
	toSerialize["signature"] = o.Signature
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize, nil
}

func (o *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"externalTransactionId",
		"paymentId",
		"signature",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq := _UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq)

	if err != nil {
		return err
	}

	*o = UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq(varUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq)

	return err
}

type NullableUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq struct {
	value *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq
	isSet bool
}

func (v NullableUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) Get() *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq {
	return v.value
}

func (v *NullableUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) Set(val *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) {
	v.value = val
	v.isSet = true
}

func (v NullableUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) IsSet() bool {
	return v.isSet
}

func (v *NullableUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq(val *UnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) *NullableUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq {
	return &NullableUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq{value: val, isSet: true}
}

func (v NullableUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnibeeApiMerchantPaymentExternalGatewayPaymentMarkFailedReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


