/*
OpenAPI UniBee

UniBee Api Server

API version: daily,buildtime:202511041032
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unibee

import (
	"encoding/json"
)

// checks if the UnibeeApiBeanDetailCreditNoteDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnibeeApiBeanDetailCreditNoteDetail{}

// UnibeeApiBeanDetailCreditNoteDetail struct for UnibeeApiBeanDetailCreditNoteDetail
type UnibeeApiBeanDetailCreditNoteDetail struct {
	BizType *int32 `json:"bizType,omitempty"`
	CountryCode *string `json:"countryCode,omitempty"`
	// create from
	CreateFrom *string `json:"createFrom,omitempty"`
	CreateTime *int64 `json:"createTime,omitempty"`
	// Currency
	Currency *string `json:"currency,omitempty"`
	Discount *UnibeeApiBeanMerchantDiscountCode `json:"discount,omitempty"`
	// DiscountAmount,Cents
	DiscountAmount *int64 `json:"discountAmount,omitempty"`
	DiscountCode *string `json:"discountCode,omitempty"`
	FinishTime *int64 `json:"finishTime,omitempty"`
	Gateway *UnibeeApiBeanDetailGateway `json:"gateway,omitempty"`
	// Id
	GatewayId *int64 `json:"gatewayId,omitempty"`
	Id *int64 `json:"id,omitempty"`
	// InvoiceId
	InvoiceId *string `json:"invoiceId,omitempty"`
	// InvoiceName
	InvoiceName *string `json:"invoiceName,omitempty"`
	// lines json data
	Lines []UnibeeApiBeanInvoiceItemSimplify `json:"lines,omitempty"`
	// Link
	Link *string `json:"link,omitempty"`
	// MerchantId
	MerchantId *int64 `json:"merchantId,omitempty"`
	Message *string `json:"message,omitempty"`
	// Metadata，Map
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	// OriginAmount,Cents
	OriginAmount *int64 `json:"originAmount,omitempty"`
	OriginalPaymentInvoice *UnibeeApiBeanInvoice `json:"originalPaymentInvoice,omitempty"`
	PaidTime *int64 `json:"paidTime,omitempty"`
	// partial credit paid amount
	PartialCreditPaidAmount *int64 `json:"partialCreditPaidAmount,omitempty"`
	Payment *UnibeeApiBeanPayment `json:"payment,omitempty"`
	// PaymentId
	PaymentId *string `json:"paymentId,omitempty"`
	// period_end
	PeriodEnd *int64 `json:"periodEnd,omitempty"`
	// period_start
	PeriodStart *int64 `json:"periodStart,omitempty"`
	PlanSnapshot *UnibeeApiBeanInvoicePlanSnapshot `json:"planSnapshot,omitempty"`
	ProductName *string `json:"productName,omitempty"`
	// promo credit discount amount
	PromoCreditDiscountAmount *int64 `json:"promoCreditDiscountAmount,omitempty"`
	PromoCreditTransaction *UnibeeApiBeanCreditTransaction `json:"promoCreditTransaction,omitempty"`
	Refund *UnibeeApiBeanRefund `json:"refund,omitempty"`
	// refundId
	RefundId *string `json:"refundId,omitempty"`
	// Status，1-pending｜2-processing｜3-paid | 4-failed | 5-cancelled
	Status *int32 `json:"status,omitempty"`
	Subscription *UnibeeApiBeanSubscription `json:"subscription,omitempty"`
	// SubscriptionAmount,Cents
	SubscriptionAmount *int64 `json:"subscriptionAmount,omitempty"`
	// SubscriptionAmountExcludingTax,Cents
	SubscriptionAmountExcludingTax *int64 `json:"subscriptionAmountExcludingTax,omitempty"`
	// SubscriptionId
	SubscriptionId *string `json:"subscriptionId,omitempty"`
	// TaxAmount,Cents
	TaxAmount *int64 `json:"taxAmount,omitempty"`
	// TaxPercentage，1000 = 10%
	TaxPercentage *int64 `json:"taxPercentage,omitempty"`
	// TotalAmount,Cents
	TotalAmount *int64 `json:"totalAmount,omitempty"`
	// TotalAmountExcludingTax,Cents
	TotalAmountExcludingTax *int64 `json:"totalAmountExcludingTax,omitempty"`
	// UserId
	UserId *int64 `json:"userId,omitempty"`
	UserSnapshot *UnibeeApiBeanUserAccount `json:"userSnapshot,omitempty"`
	VatNumber *string `json:"vatNumber,omitempty"`
}

// NewUnibeeApiBeanDetailCreditNoteDetail instantiates a new UnibeeApiBeanDetailCreditNoteDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnibeeApiBeanDetailCreditNoteDetail() *UnibeeApiBeanDetailCreditNoteDetail {
	this := UnibeeApiBeanDetailCreditNoteDetail{}
	return &this
}

// NewUnibeeApiBeanDetailCreditNoteDetailWithDefaults instantiates a new UnibeeApiBeanDetailCreditNoteDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnibeeApiBeanDetailCreditNoteDetailWithDefaults() *UnibeeApiBeanDetailCreditNoteDetail {
	this := UnibeeApiBeanDetailCreditNoteDetail{}
	return &this
}

// GetBizType returns the BizType field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetBizType() int32 {
	if o == nil || IsNil(o.BizType) {
		var ret int32
		return ret
	}
	return *o.BizType
}

// GetBizTypeOk returns a tuple with the BizType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetBizTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.BizType) {
		return nil, false
	}
	return o.BizType, true
}

// HasBizType returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasBizType() bool {
	if o != nil && !IsNil(o.BizType) {
		return true
	}

	return false
}

// SetBizType gets a reference to the given int32 and assigns it to the BizType field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetBizType(v int32) {
	o.BizType = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetCreateFrom returns the CreateFrom field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetCreateFrom() string {
	if o == nil || IsNil(o.CreateFrom) {
		var ret string
		return ret
	}
	return *o.CreateFrom
}

// GetCreateFromOk returns a tuple with the CreateFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetCreateFromOk() (*string, bool) {
	if o == nil || IsNil(o.CreateFrom) {
		return nil, false
	}
	return o.CreateFrom, true
}

// HasCreateFrom returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasCreateFrom() bool {
	if o != nil && !IsNil(o.CreateFrom) {
		return true
	}

	return false
}

// SetCreateFrom gets a reference to the given string and assigns it to the CreateFrom field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetCreateFrom(v string) {
	o.CreateFrom = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetCreateTime() int64 {
	if o == nil || IsNil(o.CreateTime) {
		var ret int64
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetCreateTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given int64 and assigns it to the CreateTime field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetCreateTime(v int64) {
	o.CreateTime = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetCurrency(v string) {
	o.Currency = &v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetDiscount() UnibeeApiBeanMerchantDiscountCode {
	if o == nil || IsNil(o.Discount) {
		var ret UnibeeApiBeanMerchantDiscountCode
		return ret
	}
	return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetDiscountOk() (*UnibeeApiBeanMerchantDiscountCode, bool) {
	if o == nil || IsNil(o.Discount) {
		return nil, false
	}
	return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasDiscount() bool {
	if o != nil && !IsNil(o.Discount) {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given UnibeeApiBeanMerchantDiscountCode and assigns it to the Discount field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetDiscount(v UnibeeApiBeanMerchantDiscountCode) {
	o.Discount = &v
}

// GetDiscountAmount returns the DiscountAmount field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetDiscountAmount() int64 {
	if o == nil || IsNil(o.DiscountAmount) {
		var ret int64
		return ret
	}
	return *o.DiscountAmount
}

// GetDiscountAmountOk returns a tuple with the DiscountAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetDiscountAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.DiscountAmount) {
		return nil, false
	}
	return o.DiscountAmount, true
}

// HasDiscountAmount returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasDiscountAmount() bool {
	if o != nil && !IsNil(o.DiscountAmount) {
		return true
	}

	return false
}

// SetDiscountAmount gets a reference to the given int64 and assigns it to the DiscountAmount field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetDiscountAmount(v int64) {
	o.DiscountAmount = &v
}

// GetDiscountCode returns the DiscountCode field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetDiscountCode() string {
	if o == nil || IsNil(o.DiscountCode) {
		var ret string
		return ret
	}
	return *o.DiscountCode
}

// GetDiscountCodeOk returns a tuple with the DiscountCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetDiscountCodeOk() (*string, bool) {
	if o == nil || IsNil(o.DiscountCode) {
		return nil, false
	}
	return o.DiscountCode, true
}

// HasDiscountCode returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasDiscountCode() bool {
	if o != nil && !IsNil(o.DiscountCode) {
		return true
	}

	return false
}

// SetDiscountCode gets a reference to the given string and assigns it to the DiscountCode field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetDiscountCode(v string) {
	o.DiscountCode = &v
}

// GetFinishTime returns the FinishTime field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetFinishTime() int64 {
	if o == nil || IsNil(o.FinishTime) {
		var ret int64
		return ret
	}
	return *o.FinishTime
}

// GetFinishTimeOk returns a tuple with the FinishTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetFinishTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.FinishTime) {
		return nil, false
	}
	return o.FinishTime, true
}

// HasFinishTime returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasFinishTime() bool {
	if o != nil && !IsNil(o.FinishTime) {
		return true
	}

	return false
}

// SetFinishTime gets a reference to the given int64 and assigns it to the FinishTime field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetFinishTime(v int64) {
	o.FinishTime = &v
}

// GetGateway returns the Gateway field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetGateway() UnibeeApiBeanDetailGateway {
	if o == nil || IsNil(o.Gateway) {
		var ret UnibeeApiBeanDetailGateway
		return ret
	}
	return *o.Gateway
}

// GetGatewayOk returns a tuple with the Gateway field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetGatewayOk() (*UnibeeApiBeanDetailGateway, bool) {
	if o == nil || IsNil(o.Gateway) {
		return nil, false
	}
	return o.Gateway, true
}

// HasGateway returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasGateway() bool {
	if o != nil && !IsNil(o.Gateway) {
		return true
	}

	return false
}

// SetGateway gets a reference to the given UnibeeApiBeanDetailGateway and assigns it to the Gateway field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetGateway(v UnibeeApiBeanDetailGateway) {
	o.Gateway = &v
}

// GetGatewayId returns the GatewayId field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetGatewayId() int64 {
	if o == nil || IsNil(o.GatewayId) {
		var ret int64
		return ret
	}
	return *o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetGatewayIdOk() (*int64, bool) {
	if o == nil || IsNil(o.GatewayId) {
		return nil, false
	}
	return o.GatewayId, true
}

// HasGatewayId returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasGatewayId() bool {
	if o != nil && !IsNil(o.GatewayId) {
		return true
	}

	return false
}

// SetGatewayId gets a reference to the given int64 and assigns it to the GatewayId field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetGatewayId(v int64) {
	o.GatewayId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetId(v int64) {
	o.Id = &v
}

// GetInvoiceId returns the InvoiceId field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetInvoiceId() string {
	if o == nil || IsNil(o.InvoiceId) {
		var ret string
		return ret
	}
	return *o.InvoiceId
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetInvoiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceId) {
		return nil, false
	}
	return o.InvoiceId, true
}

// HasInvoiceId returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasInvoiceId() bool {
	if o != nil && !IsNil(o.InvoiceId) {
		return true
	}

	return false
}

// SetInvoiceId gets a reference to the given string and assigns it to the InvoiceId field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetInvoiceId(v string) {
	o.InvoiceId = &v
}

// GetInvoiceName returns the InvoiceName field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetInvoiceName() string {
	if o == nil || IsNil(o.InvoiceName) {
		var ret string
		return ret
	}
	return *o.InvoiceName
}

// GetInvoiceNameOk returns a tuple with the InvoiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetInvoiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceName) {
		return nil, false
	}
	return o.InvoiceName, true
}

// HasInvoiceName returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasInvoiceName() bool {
	if o != nil && !IsNil(o.InvoiceName) {
		return true
	}

	return false
}

// SetInvoiceName gets a reference to the given string and assigns it to the InvoiceName field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetInvoiceName(v string) {
	o.InvoiceName = &v
}

// GetLines returns the Lines field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetLines() []UnibeeApiBeanInvoiceItemSimplify {
	if o == nil || IsNil(o.Lines) {
		var ret []UnibeeApiBeanInvoiceItemSimplify
		return ret
	}
	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetLinesOk() ([]UnibeeApiBeanInvoiceItemSimplify, bool) {
	if o == nil || IsNil(o.Lines) {
		return nil, false
	}
	return o.Lines, true
}

// HasLines returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasLines() bool {
	if o != nil && !IsNil(o.Lines) {
		return true
	}

	return false
}

// SetLines gets a reference to the given []UnibeeApiBeanInvoiceItemSimplify and assigns it to the Lines field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetLines(v []UnibeeApiBeanInvoiceItemSimplify) {
	o.Lines = v
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetLink() string {
	if o == nil || IsNil(o.Link) {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetLinkOk() (*string, bool) {
	if o == nil || IsNil(o.Link) {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasLink() bool {
	if o != nil && !IsNil(o.Link) {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetLink(v string) {
	o.Link = &v
}

// GetMerchantId returns the MerchantId field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetMerchantId() int64 {
	if o == nil || IsNil(o.MerchantId) {
		var ret int64
		return ret
	}
	return *o.MerchantId
}

// GetMerchantIdOk returns a tuple with the MerchantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetMerchantIdOk() (*int64, bool) {
	if o == nil || IsNil(o.MerchantId) {
		return nil, false
	}
	return o.MerchantId, true
}

// HasMerchantId returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasMerchantId() bool {
	if o != nil && !IsNil(o.MerchantId) {
		return true
	}

	return false
}

// SetMerchantId gets a reference to the given int64 and assigns it to the MerchantId field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetMerchantId(v int64) {
	o.MerchantId = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetMessage(v string) {
	o.Message = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetMetadata(v map[string]interface{}) {
	o.Metadata = &v
}

// GetOriginAmount returns the OriginAmount field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetOriginAmount() int64 {
	if o == nil || IsNil(o.OriginAmount) {
		var ret int64
		return ret
	}
	return *o.OriginAmount
}

// GetOriginAmountOk returns a tuple with the OriginAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetOriginAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.OriginAmount) {
		return nil, false
	}
	return o.OriginAmount, true
}

// HasOriginAmount returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasOriginAmount() bool {
	if o != nil && !IsNil(o.OriginAmount) {
		return true
	}

	return false
}

// SetOriginAmount gets a reference to the given int64 and assigns it to the OriginAmount field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetOriginAmount(v int64) {
	o.OriginAmount = &v
}

// GetOriginalPaymentInvoice returns the OriginalPaymentInvoice field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetOriginalPaymentInvoice() UnibeeApiBeanInvoice {
	if o == nil || IsNil(o.OriginalPaymentInvoice) {
		var ret UnibeeApiBeanInvoice
		return ret
	}
	return *o.OriginalPaymentInvoice
}

// GetOriginalPaymentInvoiceOk returns a tuple with the OriginalPaymentInvoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetOriginalPaymentInvoiceOk() (*UnibeeApiBeanInvoice, bool) {
	if o == nil || IsNil(o.OriginalPaymentInvoice) {
		return nil, false
	}
	return o.OriginalPaymentInvoice, true
}

// HasOriginalPaymentInvoice returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasOriginalPaymentInvoice() bool {
	if o != nil && !IsNil(o.OriginalPaymentInvoice) {
		return true
	}

	return false
}

// SetOriginalPaymentInvoice gets a reference to the given UnibeeApiBeanInvoice and assigns it to the OriginalPaymentInvoice field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetOriginalPaymentInvoice(v UnibeeApiBeanInvoice) {
	o.OriginalPaymentInvoice = &v
}

// GetPaidTime returns the PaidTime field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPaidTime() int64 {
	if o == nil || IsNil(o.PaidTime) {
		var ret int64
		return ret
	}
	return *o.PaidTime
}

// GetPaidTimeOk returns a tuple with the PaidTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPaidTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.PaidTime) {
		return nil, false
	}
	return o.PaidTime, true
}

// HasPaidTime returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasPaidTime() bool {
	if o != nil && !IsNil(o.PaidTime) {
		return true
	}

	return false
}

// SetPaidTime gets a reference to the given int64 and assigns it to the PaidTime field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetPaidTime(v int64) {
	o.PaidTime = &v
}

// GetPartialCreditPaidAmount returns the PartialCreditPaidAmount field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPartialCreditPaidAmount() int64 {
	if o == nil || IsNil(o.PartialCreditPaidAmount) {
		var ret int64
		return ret
	}
	return *o.PartialCreditPaidAmount
}

// GetPartialCreditPaidAmountOk returns a tuple with the PartialCreditPaidAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPartialCreditPaidAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.PartialCreditPaidAmount) {
		return nil, false
	}
	return o.PartialCreditPaidAmount, true
}

// HasPartialCreditPaidAmount returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasPartialCreditPaidAmount() bool {
	if o != nil && !IsNil(o.PartialCreditPaidAmount) {
		return true
	}

	return false
}

// SetPartialCreditPaidAmount gets a reference to the given int64 and assigns it to the PartialCreditPaidAmount field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetPartialCreditPaidAmount(v int64) {
	o.PartialCreditPaidAmount = &v
}

// GetPayment returns the Payment field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPayment() UnibeeApiBeanPayment {
	if o == nil || IsNil(o.Payment) {
		var ret UnibeeApiBeanPayment
		return ret
	}
	return *o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPaymentOk() (*UnibeeApiBeanPayment, bool) {
	if o == nil || IsNil(o.Payment) {
		return nil, false
	}
	return o.Payment, true
}

// HasPayment returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasPayment() bool {
	if o != nil && !IsNil(o.Payment) {
		return true
	}

	return false
}

// SetPayment gets a reference to the given UnibeeApiBeanPayment and assigns it to the Payment field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetPayment(v UnibeeApiBeanPayment) {
	o.Payment = &v
}

// GetPaymentId returns the PaymentId field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPaymentId() string {
	if o == nil || IsNil(o.PaymentId) {
		var ret string
		return ret
	}
	return *o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPaymentIdOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentId) {
		return nil, false
	}
	return o.PaymentId, true
}

// HasPaymentId returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasPaymentId() bool {
	if o != nil && !IsNil(o.PaymentId) {
		return true
	}

	return false
}

// SetPaymentId gets a reference to the given string and assigns it to the PaymentId field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetPaymentId(v string) {
	o.PaymentId = &v
}

// GetPeriodEnd returns the PeriodEnd field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPeriodEnd() int64 {
	if o == nil || IsNil(o.PeriodEnd) {
		var ret int64
		return ret
	}
	return *o.PeriodEnd
}

// GetPeriodEndOk returns a tuple with the PeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPeriodEndOk() (*int64, bool) {
	if o == nil || IsNil(o.PeriodEnd) {
		return nil, false
	}
	return o.PeriodEnd, true
}

// HasPeriodEnd returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasPeriodEnd() bool {
	if o != nil && !IsNil(o.PeriodEnd) {
		return true
	}

	return false
}

// SetPeriodEnd gets a reference to the given int64 and assigns it to the PeriodEnd field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetPeriodEnd(v int64) {
	o.PeriodEnd = &v
}

// GetPeriodStart returns the PeriodStart field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPeriodStart() int64 {
	if o == nil || IsNil(o.PeriodStart) {
		var ret int64
		return ret
	}
	return *o.PeriodStart
}

// GetPeriodStartOk returns a tuple with the PeriodStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPeriodStartOk() (*int64, bool) {
	if o == nil || IsNil(o.PeriodStart) {
		return nil, false
	}
	return o.PeriodStart, true
}

// HasPeriodStart returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasPeriodStart() bool {
	if o != nil && !IsNil(o.PeriodStart) {
		return true
	}

	return false
}

// SetPeriodStart gets a reference to the given int64 and assigns it to the PeriodStart field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetPeriodStart(v int64) {
	o.PeriodStart = &v
}

// GetPlanSnapshot returns the PlanSnapshot field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPlanSnapshot() UnibeeApiBeanInvoicePlanSnapshot {
	if o == nil || IsNil(o.PlanSnapshot) {
		var ret UnibeeApiBeanInvoicePlanSnapshot
		return ret
	}
	return *o.PlanSnapshot
}

// GetPlanSnapshotOk returns a tuple with the PlanSnapshot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPlanSnapshotOk() (*UnibeeApiBeanInvoicePlanSnapshot, bool) {
	if o == nil || IsNil(o.PlanSnapshot) {
		return nil, false
	}
	return o.PlanSnapshot, true
}

// HasPlanSnapshot returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasPlanSnapshot() bool {
	if o != nil && !IsNil(o.PlanSnapshot) {
		return true
	}

	return false
}

// SetPlanSnapshot gets a reference to the given UnibeeApiBeanInvoicePlanSnapshot and assigns it to the PlanSnapshot field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetPlanSnapshot(v UnibeeApiBeanInvoicePlanSnapshot) {
	o.PlanSnapshot = &v
}

// GetProductName returns the ProductName field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetProductName() string {
	if o == nil || IsNil(o.ProductName) {
		var ret string
		return ret
	}
	return *o.ProductName
}

// GetProductNameOk returns a tuple with the ProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetProductNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProductName) {
		return nil, false
	}
	return o.ProductName, true
}

// HasProductName returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasProductName() bool {
	if o != nil && !IsNil(o.ProductName) {
		return true
	}

	return false
}

// SetProductName gets a reference to the given string and assigns it to the ProductName field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetProductName(v string) {
	o.ProductName = &v
}

// GetPromoCreditDiscountAmount returns the PromoCreditDiscountAmount field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPromoCreditDiscountAmount() int64 {
	if o == nil || IsNil(o.PromoCreditDiscountAmount) {
		var ret int64
		return ret
	}
	return *o.PromoCreditDiscountAmount
}

// GetPromoCreditDiscountAmountOk returns a tuple with the PromoCreditDiscountAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPromoCreditDiscountAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.PromoCreditDiscountAmount) {
		return nil, false
	}
	return o.PromoCreditDiscountAmount, true
}

// HasPromoCreditDiscountAmount returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasPromoCreditDiscountAmount() bool {
	if o != nil && !IsNil(o.PromoCreditDiscountAmount) {
		return true
	}

	return false
}

// SetPromoCreditDiscountAmount gets a reference to the given int64 and assigns it to the PromoCreditDiscountAmount field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetPromoCreditDiscountAmount(v int64) {
	o.PromoCreditDiscountAmount = &v
}

// GetPromoCreditTransaction returns the PromoCreditTransaction field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPromoCreditTransaction() UnibeeApiBeanCreditTransaction {
	if o == nil || IsNil(o.PromoCreditTransaction) {
		var ret UnibeeApiBeanCreditTransaction
		return ret
	}
	return *o.PromoCreditTransaction
}

// GetPromoCreditTransactionOk returns a tuple with the PromoCreditTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetPromoCreditTransactionOk() (*UnibeeApiBeanCreditTransaction, bool) {
	if o == nil || IsNil(o.PromoCreditTransaction) {
		return nil, false
	}
	return o.PromoCreditTransaction, true
}

// HasPromoCreditTransaction returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasPromoCreditTransaction() bool {
	if o != nil && !IsNil(o.PromoCreditTransaction) {
		return true
	}

	return false
}

// SetPromoCreditTransaction gets a reference to the given UnibeeApiBeanCreditTransaction and assigns it to the PromoCreditTransaction field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetPromoCreditTransaction(v UnibeeApiBeanCreditTransaction) {
	o.PromoCreditTransaction = &v
}

// GetRefund returns the Refund field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetRefund() UnibeeApiBeanRefund {
	if o == nil || IsNil(o.Refund) {
		var ret UnibeeApiBeanRefund
		return ret
	}
	return *o.Refund
}

// GetRefundOk returns a tuple with the Refund field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetRefundOk() (*UnibeeApiBeanRefund, bool) {
	if o == nil || IsNil(o.Refund) {
		return nil, false
	}
	return o.Refund, true
}

// HasRefund returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasRefund() bool {
	if o != nil && !IsNil(o.Refund) {
		return true
	}

	return false
}

// SetRefund gets a reference to the given UnibeeApiBeanRefund and assigns it to the Refund field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetRefund(v UnibeeApiBeanRefund) {
	o.Refund = &v
}

// GetRefundId returns the RefundId field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetRefundId() string {
	if o == nil || IsNil(o.RefundId) {
		var ret string
		return ret
	}
	return *o.RefundId
}

// GetRefundIdOk returns a tuple with the RefundId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetRefundIdOk() (*string, bool) {
	if o == nil || IsNil(o.RefundId) {
		return nil, false
	}
	return o.RefundId, true
}

// HasRefundId returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasRefundId() bool {
	if o != nil && !IsNil(o.RefundId) {
		return true
	}

	return false
}

// SetRefundId gets a reference to the given string and assigns it to the RefundId field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetRefundId(v string) {
	o.RefundId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetStatus(v int32) {
	o.Status = &v
}

// GetSubscription returns the Subscription field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetSubscription() UnibeeApiBeanSubscription {
	if o == nil || IsNil(o.Subscription) {
		var ret UnibeeApiBeanSubscription
		return ret
	}
	return *o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetSubscriptionOk() (*UnibeeApiBeanSubscription, bool) {
	if o == nil || IsNil(o.Subscription) {
		return nil, false
	}
	return o.Subscription, true
}

// HasSubscription returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasSubscription() bool {
	if o != nil && !IsNil(o.Subscription) {
		return true
	}

	return false
}

// SetSubscription gets a reference to the given UnibeeApiBeanSubscription and assigns it to the Subscription field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetSubscription(v UnibeeApiBeanSubscription) {
	o.Subscription = &v
}

// GetSubscriptionAmount returns the SubscriptionAmount field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetSubscriptionAmount() int64 {
	if o == nil || IsNil(o.SubscriptionAmount) {
		var ret int64
		return ret
	}
	return *o.SubscriptionAmount
}

// GetSubscriptionAmountOk returns a tuple with the SubscriptionAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetSubscriptionAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.SubscriptionAmount) {
		return nil, false
	}
	return o.SubscriptionAmount, true
}

// HasSubscriptionAmount returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasSubscriptionAmount() bool {
	if o != nil && !IsNil(o.SubscriptionAmount) {
		return true
	}

	return false
}

// SetSubscriptionAmount gets a reference to the given int64 and assigns it to the SubscriptionAmount field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetSubscriptionAmount(v int64) {
	o.SubscriptionAmount = &v
}

// GetSubscriptionAmountExcludingTax returns the SubscriptionAmountExcludingTax field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetSubscriptionAmountExcludingTax() int64 {
	if o == nil || IsNil(o.SubscriptionAmountExcludingTax) {
		var ret int64
		return ret
	}
	return *o.SubscriptionAmountExcludingTax
}

// GetSubscriptionAmountExcludingTaxOk returns a tuple with the SubscriptionAmountExcludingTax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetSubscriptionAmountExcludingTaxOk() (*int64, bool) {
	if o == nil || IsNil(o.SubscriptionAmountExcludingTax) {
		return nil, false
	}
	return o.SubscriptionAmountExcludingTax, true
}

// HasSubscriptionAmountExcludingTax returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasSubscriptionAmountExcludingTax() bool {
	if o != nil && !IsNil(o.SubscriptionAmountExcludingTax) {
		return true
	}

	return false
}

// SetSubscriptionAmountExcludingTax gets a reference to the given int64 and assigns it to the SubscriptionAmountExcludingTax field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetSubscriptionAmountExcludingTax(v int64) {
	o.SubscriptionAmountExcludingTax = &v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetTaxAmount returns the TaxAmount field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetTaxAmount() int64 {
	if o == nil || IsNil(o.TaxAmount) {
		var ret int64
		return ret
	}
	return *o.TaxAmount
}

// GetTaxAmountOk returns a tuple with the TaxAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetTaxAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.TaxAmount) {
		return nil, false
	}
	return o.TaxAmount, true
}

// HasTaxAmount returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasTaxAmount() bool {
	if o != nil && !IsNil(o.TaxAmount) {
		return true
	}

	return false
}

// SetTaxAmount gets a reference to the given int64 and assigns it to the TaxAmount field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetTaxAmount(v int64) {
	o.TaxAmount = &v
}

// GetTaxPercentage returns the TaxPercentage field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetTaxPercentage() int64 {
	if o == nil || IsNil(o.TaxPercentage) {
		var ret int64
		return ret
	}
	return *o.TaxPercentage
}

// GetTaxPercentageOk returns a tuple with the TaxPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetTaxPercentageOk() (*int64, bool) {
	if o == nil || IsNil(o.TaxPercentage) {
		return nil, false
	}
	return o.TaxPercentage, true
}

// HasTaxPercentage returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasTaxPercentage() bool {
	if o != nil && !IsNil(o.TaxPercentage) {
		return true
	}

	return false
}

// SetTaxPercentage gets a reference to the given int64 and assigns it to the TaxPercentage field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetTaxPercentage(v int64) {
	o.TaxPercentage = &v
}

// GetTotalAmount returns the TotalAmount field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetTotalAmount() int64 {
	if o == nil || IsNil(o.TotalAmount) {
		var ret int64
		return ret
	}
	return *o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetTotalAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalAmount) {
		return nil, false
	}
	return o.TotalAmount, true
}

// HasTotalAmount returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasTotalAmount() bool {
	if o != nil && !IsNil(o.TotalAmount) {
		return true
	}

	return false
}

// SetTotalAmount gets a reference to the given int64 and assigns it to the TotalAmount field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetTotalAmount(v int64) {
	o.TotalAmount = &v
}

// GetTotalAmountExcludingTax returns the TotalAmountExcludingTax field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetTotalAmountExcludingTax() int64 {
	if o == nil || IsNil(o.TotalAmountExcludingTax) {
		var ret int64
		return ret
	}
	return *o.TotalAmountExcludingTax
}

// GetTotalAmountExcludingTaxOk returns a tuple with the TotalAmountExcludingTax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetTotalAmountExcludingTaxOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalAmountExcludingTax) {
		return nil, false
	}
	return o.TotalAmountExcludingTax, true
}

// HasTotalAmountExcludingTax returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasTotalAmountExcludingTax() bool {
	if o != nil && !IsNil(o.TotalAmountExcludingTax) {
		return true
	}

	return false
}

// SetTotalAmountExcludingTax gets a reference to the given int64 and assigns it to the TotalAmountExcludingTax field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetTotalAmountExcludingTax(v int64) {
	o.TotalAmountExcludingTax = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetUserId() int64 {
	if o == nil || IsNil(o.UserId) {
		var ret int64
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetUserIdOk() (*int64, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int64 and assigns it to the UserId field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetUserId(v int64) {
	o.UserId = &v
}

// GetUserSnapshot returns the UserSnapshot field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetUserSnapshot() UnibeeApiBeanUserAccount {
	if o == nil || IsNil(o.UserSnapshot) {
		var ret UnibeeApiBeanUserAccount
		return ret
	}
	return *o.UserSnapshot
}

// GetUserSnapshotOk returns a tuple with the UserSnapshot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetUserSnapshotOk() (*UnibeeApiBeanUserAccount, bool) {
	if o == nil || IsNil(o.UserSnapshot) {
		return nil, false
	}
	return o.UserSnapshot, true
}

// HasUserSnapshot returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasUserSnapshot() bool {
	if o != nil && !IsNil(o.UserSnapshot) {
		return true
	}

	return false
}

// SetUserSnapshot gets a reference to the given UnibeeApiBeanUserAccount and assigns it to the UserSnapshot field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetUserSnapshot(v UnibeeApiBeanUserAccount) {
	o.UserSnapshot = &v
}

// GetVatNumber returns the VatNumber field value if set, zero value otherwise.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetVatNumber() string {
	if o == nil || IsNil(o.VatNumber) {
		var ret string
		return ret
	}
	return *o.VatNumber
}

// GetVatNumberOk returns a tuple with the VatNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) GetVatNumberOk() (*string, bool) {
	if o == nil || IsNil(o.VatNumber) {
		return nil, false
	}
	return o.VatNumber, true
}

// HasVatNumber returns a boolean if a field has been set.
func (o *UnibeeApiBeanDetailCreditNoteDetail) HasVatNumber() bool {
	if o != nil && !IsNil(o.VatNumber) {
		return true
	}

	return false
}

// SetVatNumber gets a reference to the given string and assigns it to the VatNumber field.
func (o *UnibeeApiBeanDetailCreditNoteDetail) SetVatNumber(v string) {
	o.VatNumber = &v
}

func (o UnibeeApiBeanDetailCreditNoteDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnibeeApiBeanDetailCreditNoteDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BizType) {
		toSerialize["bizType"] = o.BizType
	}
	if !IsNil(o.CountryCode) {
		toSerialize["countryCode"] = o.CountryCode
	}
	if !IsNil(o.CreateFrom) {
		toSerialize["createFrom"] = o.CreateFrom
	}
	if !IsNil(o.CreateTime) {
		toSerialize["createTime"] = o.CreateTime
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Discount) {
		toSerialize["discount"] = o.Discount
	}
	if !IsNil(o.DiscountAmount) {
		toSerialize["discountAmount"] = o.DiscountAmount
	}
	if !IsNil(o.DiscountCode) {
		toSerialize["discountCode"] = o.DiscountCode
	}
	if !IsNil(o.FinishTime) {
		toSerialize["finishTime"] = o.FinishTime
	}
	if !IsNil(o.Gateway) {
		toSerialize["gateway"] = o.Gateway
	}
	if !IsNil(o.GatewayId) {
		toSerialize["gatewayId"] = o.GatewayId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InvoiceId) {
		toSerialize["invoiceId"] = o.InvoiceId
	}
	if !IsNil(o.InvoiceName) {
		toSerialize["invoiceName"] = o.InvoiceName
	}
	if !IsNil(o.Lines) {
		toSerialize["lines"] = o.Lines
	}
	if !IsNil(o.Link) {
		toSerialize["link"] = o.Link
	}
	if !IsNil(o.MerchantId) {
		toSerialize["merchantId"] = o.MerchantId
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.OriginAmount) {
		toSerialize["originAmount"] = o.OriginAmount
	}
	if !IsNil(o.OriginalPaymentInvoice) {
		toSerialize["originalPaymentInvoice"] = o.OriginalPaymentInvoice
	}
	if !IsNil(o.PaidTime) {
		toSerialize["paidTime"] = o.PaidTime
	}
	if !IsNil(o.PartialCreditPaidAmount) {
		toSerialize["partialCreditPaidAmount"] = o.PartialCreditPaidAmount
	}
	if !IsNil(o.Payment) {
		toSerialize["payment"] = o.Payment
	}
	if !IsNil(o.PaymentId) {
		toSerialize["paymentId"] = o.PaymentId
	}
	if !IsNil(o.PeriodEnd) {
		toSerialize["periodEnd"] = o.PeriodEnd
	}
	if !IsNil(o.PeriodStart) {
		toSerialize["periodStart"] = o.PeriodStart
	}
	if !IsNil(o.PlanSnapshot) {
		toSerialize["planSnapshot"] = o.PlanSnapshot
	}
	if !IsNil(o.ProductName) {
		toSerialize["productName"] = o.ProductName
	}
	if !IsNil(o.PromoCreditDiscountAmount) {
		toSerialize["promoCreditDiscountAmount"] = o.PromoCreditDiscountAmount
	}
	if !IsNil(o.PromoCreditTransaction) {
		toSerialize["promoCreditTransaction"] = o.PromoCreditTransaction
	}
	if !IsNil(o.Refund) {
		toSerialize["refund"] = o.Refund
	}
	if !IsNil(o.RefundId) {
		toSerialize["refundId"] = o.RefundId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Subscription) {
		toSerialize["subscription"] = o.Subscription
	}
	if !IsNil(o.SubscriptionAmount) {
		toSerialize["subscriptionAmount"] = o.SubscriptionAmount
	}
	if !IsNil(o.SubscriptionAmountExcludingTax) {
		toSerialize["subscriptionAmountExcludingTax"] = o.SubscriptionAmountExcludingTax
	}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscriptionId"] = o.SubscriptionId
	}
	if !IsNil(o.TaxAmount) {
		toSerialize["taxAmount"] = o.TaxAmount
	}
	if !IsNil(o.TaxPercentage) {
		toSerialize["taxPercentage"] = o.TaxPercentage
	}
	if !IsNil(o.TotalAmount) {
		toSerialize["totalAmount"] = o.TotalAmount
	}
	if !IsNil(o.TotalAmountExcludingTax) {
		toSerialize["totalAmountExcludingTax"] = o.TotalAmountExcludingTax
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.UserSnapshot) {
		toSerialize["userSnapshot"] = o.UserSnapshot
	}
	if !IsNil(o.VatNumber) {
		toSerialize["vatNumber"] = o.VatNumber
	}
	return toSerialize, nil
}

type NullableUnibeeApiBeanDetailCreditNoteDetail struct {
	value *UnibeeApiBeanDetailCreditNoteDetail
	isSet bool
}

func (v NullableUnibeeApiBeanDetailCreditNoteDetail) Get() *UnibeeApiBeanDetailCreditNoteDetail {
	return v.value
}

func (v *NullableUnibeeApiBeanDetailCreditNoteDetail) Set(val *UnibeeApiBeanDetailCreditNoteDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableUnibeeApiBeanDetailCreditNoteDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableUnibeeApiBeanDetailCreditNoteDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnibeeApiBeanDetailCreditNoteDetail(val *UnibeeApiBeanDetailCreditNoteDetail) *NullableUnibeeApiBeanDetailCreditNoteDetail {
	return &NullableUnibeeApiBeanDetailCreditNoteDetail{value: val, isSet: true}
}

func (v NullableUnibeeApiBeanDetailCreditNoteDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnibeeApiBeanDetailCreditNoteDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


