/*
OpenAPI UniBee

UniBee Api Server

API version: daily,buildtime:202512220824
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unibee

import (
	"encoding/json"
)

// checks if the UnibeeApiMerchantMetricMetricLimitAdjustRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnibeeApiMerchantMetricMetricLimitAdjustRes{}

// UnibeeApiMerchantMetricMetricLimitAdjustRes struct for UnibeeApiMerchantMetricMetricLimitAdjustRes
type UnibeeApiMerchantMetricMetricLimitAdjustRes struct {
	Success *bool `json:"success,omitempty"`
}

// NewUnibeeApiMerchantMetricMetricLimitAdjustRes instantiates a new UnibeeApiMerchantMetricMetricLimitAdjustRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnibeeApiMerchantMetricMetricLimitAdjustRes() *UnibeeApiMerchantMetricMetricLimitAdjustRes {
	this := UnibeeApiMerchantMetricMetricLimitAdjustRes{}
	return &this
}

// NewUnibeeApiMerchantMetricMetricLimitAdjustResWithDefaults instantiates a new UnibeeApiMerchantMetricMetricLimitAdjustRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnibeeApiMerchantMetricMetricLimitAdjustResWithDefaults() *UnibeeApiMerchantMetricMetricLimitAdjustRes {
	this := UnibeeApiMerchantMetricMetricLimitAdjustRes{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UnibeeApiMerchantMetricMetricLimitAdjustRes) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantMetricMetricLimitAdjustRes) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UnibeeApiMerchantMetricMetricLimitAdjustRes) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UnibeeApiMerchantMetricMetricLimitAdjustRes) SetSuccess(v bool) {
	o.Success = &v
}

func (o UnibeeApiMerchantMetricMetricLimitAdjustRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnibeeApiMerchantMetricMetricLimitAdjustRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableUnibeeApiMerchantMetricMetricLimitAdjustRes struct {
	value *UnibeeApiMerchantMetricMetricLimitAdjustRes
	isSet bool
}

func (v NullableUnibeeApiMerchantMetricMetricLimitAdjustRes) Get() *UnibeeApiMerchantMetricMetricLimitAdjustRes {
	return v.value
}

func (v *NullableUnibeeApiMerchantMetricMetricLimitAdjustRes) Set(val *UnibeeApiMerchantMetricMetricLimitAdjustRes) {
	v.value = val
	v.isSet = true
}

func (v NullableUnibeeApiMerchantMetricMetricLimitAdjustRes) IsSet() bool {
	return v.isSet
}

func (v *NullableUnibeeApiMerchantMetricMetricLimitAdjustRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnibeeApiMerchantMetricMetricLimitAdjustRes(val *UnibeeApiMerchantMetricMetricLimitAdjustRes) *NullableUnibeeApiMerchantMetricMetricLimitAdjustRes {
	return &NullableUnibeeApiMerchantMetricMetricLimitAdjustRes{value: val, isSet: true}
}

func (v NullableUnibeeApiMerchantMetricMetricLimitAdjustRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnibeeApiMerchantMetricMetricLimitAdjustRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


