/*
OpenAPI UniBee

UniBee Api Server

API version: daily,buildtime:202512220824
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unibee

import (
	"encoding/json"
)

// checks if the UnibeeApiBeanPlanMetricLimitParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnibeeApiBeanPlanMetricLimitParam{}

// UnibeeApiBeanPlanMetricLimitParam struct for UnibeeApiBeanPlanMetricLimitParam
type UnibeeApiBeanPlanMetricLimitParam struct {
	// MetricId
	MetricId *int64 `json:"metricId,omitempty"`
	// MetricLimit
	MetricLimit *int64 `json:"metricLimit,omitempty"`
}

// NewUnibeeApiBeanPlanMetricLimitParam instantiates a new UnibeeApiBeanPlanMetricLimitParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnibeeApiBeanPlanMetricLimitParam() *UnibeeApiBeanPlanMetricLimitParam {
	this := UnibeeApiBeanPlanMetricLimitParam{}
	return &this
}

// NewUnibeeApiBeanPlanMetricLimitParamWithDefaults instantiates a new UnibeeApiBeanPlanMetricLimitParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnibeeApiBeanPlanMetricLimitParamWithDefaults() *UnibeeApiBeanPlanMetricLimitParam {
	this := UnibeeApiBeanPlanMetricLimitParam{}
	return &this
}

// GetMetricId returns the MetricId field value if set, zero value otherwise.
func (o *UnibeeApiBeanPlanMetricLimitParam) GetMetricId() int64 {
	if o == nil || IsNil(o.MetricId) {
		var ret int64
		return ret
	}
	return *o.MetricId
}

// GetMetricIdOk returns a tuple with the MetricId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanPlanMetricLimitParam) GetMetricIdOk() (*int64, bool) {
	if o == nil || IsNil(o.MetricId) {
		return nil, false
	}
	return o.MetricId, true
}

// HasMetricId returns a boolean if a field has been set.
func (o *UnibeeApiBeanPlanMetricLimitParam) HasMetricId() bool {
	if o != nil && !IsNil(o.MetricId) {
		return true
	}

	return false
}

// SetMetricId gets a reference to the given int64 and assigns it to the MetricId field.
func (o *UnibeeApiBeanPlanMetricLimitParam) SetMetricId(v int64) {
	o.MetricId = &v
}

// GetMetricLimit returns the MetricLimit field value if set, zero value otherwise.
func (o *UnibeeApiBeanPlanMetricLimitParam) GetMetricLimit() int64 {
	if o == nil || IsNil(o.MetricLimit) {
		var ret int64
		return ret
	}
	return *o.MetricLimit
}

// GetMetricLimitOk returns a tuple with the MetricLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiBeanPlanMetricLimitParam) GetMetricLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.MetricLimit) {
		return nil, false
	}
	return o.MetricLimit, true
}

// HasMetricLimit returns a boolean if a field has been set.
func (o *UnibeeApiBeanPlanMetricLimitParam) HasMetricLimit() bool {
	if o != nil && !IsNil(o.MetricLimit) {
		return true
	}

	return false
}

// SetMetricLimit gets a reference to the given int64 and assigns it to the MetricLimit field.
func (o *UnibeeApiBeanPlanMetricLimitParam) SetMetricLimit(v int64) {
	o.MetricLimit = &v
}

func (o UnibeeApiBeanPlanMetricLimitParam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnibeeApiBeanPlanMetricLimitParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetricId) {
		toSerialize["metricId"] = o.MetricId
	}
	if !IsNil(o.MetricLimit) {
		toSerialize["metricLimit"] = o.MetricLimit
	}
	return toSerialize, nil
}

type NullableUnibeeApiBeanPlanMetricLimitParam struct {
	value *UnibeeApiBeanPlanMetricLimitParam
	isSet bool
}

func (v NullableUnibeeApiBeanPlanMetricLimitParam) Get() *UnibeeApiBeanPlanMetricLimitParam {
	return v.value
}

func (v *NullableUnibeeApiBeanPlanMetricLimitParam) Set(val *UnibeeApiBeanPlanMetricLimitParam) {
	v.value = val
	v.isSet = true
}

func (v NullableUnibeeApiBeanPlanMetricLimitParam) IsSet() bool {
	return v.isSet
}

func (v *NullableUnibeeApiBeanPlanMetricLimitParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnibeeApiBeanPlanMetricLimitParam(val *UnibeeApiBeanPlanMetricLimitParam) *NullableUnibeeApiBeanPlanMetricLimitParam {
	return &NullableUnibeeApiBeanPlanMetricLimitParam{value: val, isSet: true}
}

func (v NullableUnibeeApiBeanPlanMetricLimitParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnibeeApiBeanPlanMetricLimitParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


