/*
OpenAPI UniBee

UniBee Api Server

API version: daily,buildtime:202602230711
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unibee

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnibeeApiMerchantProfileUpdateCnameDomainReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnibeeApiMerchantProfileUpdateCnameDomainReq{}

// UnibeeApiMerchantProfileUpdateCnameDomainReq struct for UnibeeApiMerchantProfileUpdateCnameDomainReq
type UnibeeApiMerchantProfileUpdateCnameDomainReq struct {
	// CNAME domain
	Domain string `json:"domain"`
}

type _UnibeeApiMerchantProfileUpdateCnameDomainReq UnibeeApiMerchantProfileUpdateCnameDomainReq

// NewUnibeeApiMerchantProfileUpdateCnameDomainReq instantiates a new UnibeeApiMerchantProfileUpdateCnameDomainReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnibeeApiMerchantProfileUpdateCnameDomainReq(domain string) *UnibeeApiMerchantProfileUpdateCnameDomainReq {
	this := UnibeeApiMerchantProfileUpdateCnameDomainReq{}
	this.Domain = domain
	return &this
}

// NewUnibeeApiMerchantProfileUpdateCnameDomainReqWithDefaults instantiates a new UnibeeApiMerchantProfileUpdateCnameDomainReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnibeeApiMerchantProfileUpdateCnameDomainReqWithDefaults() *UnibeeApiMerchantProfileUpdateCnameDomainReq {
	this := UnibeeApiMerchantProfileUpdateCnameDomainReq{}
	return &this
}

// GetDomain returns the Domain field value
func (o *UnibeeApiMerchantProfileUpdateCnameDomainReq) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantProfileUpdateCnameDomainReq) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *UnibeeApiMerchantProfileUpdateCnameDomainReq) SetDomain(v string) {
	o.Domain = v
}

func (o UnibeeApiMerchantProfileUpdateCnameDomainReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnibeeApiMerchantProfileUpdateCnameDomainReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	return toSerialize, nil
}

func (o *UnibeeApiMerchantProfileUpdateCnameDomainReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnibeeApiMerchantProfileUpdateCnameDomainReq := _UnibeeApiMerchantProfileUpdateCnameDomainReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varUnibeeApiMerchantProfileUpdateCnameDomainReq)

	if err != nil {
		return err
	}

	*o = UnibeeApiMerchantProfileUpdateCnameDomainReq(varUnibeeApiMerchantProfileUpdateCnameDomainReq)

	return err
}

type NullableUnibeeApiMerchantProfileUpdateCnameDomainReq struct {
	value *UnibeeApiMerchantProfileUpdateCnameDomainReq
	isSet bool
}

func (v NullableUnibeeApiMerchantProfileUpdateCnameDomainReq) Get() *UnibeeApiMerchantProfileUpdateCnameDomainReq {
	return v.value
}

func (v *NullableUnibeeApiMerchantProfileUpdateCnameDomainReq) Set(val *UnibeeApiMerchantProfileUpdateCnameDomainReq) {
	v.value = val
	v.isSet = true
}

func (v NullableUnibeeApiMerchantProfileUpdateCnameDomainReq) IsSet() bool {
	return v.isSet
}

func (v *NullableUnibeeApiMerchantProfileUpdateCnameDomainReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnibeeApiMerchantProfileUpdateCnameDomainReq(val *UnibeeApiMerchantProfileUpdateCnameDomainReq) *NullableUnibeeApiMerchantProfileUpdateCnameDomainReq {
	return &NullableUnibeeApiMerchantProfileUpdateCnameDomainReq{value: val, isSet: true}
}

func (v NullableUnibeeApiMerchantProfileUpdateCnameDomainReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnibeeApiMerchantProfileUpdateCnameDomainReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


