/*
OpenAPI UniBee

This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UnibeeApiMerchantPaymentTimeLineListRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnibeeApiMerchantPaymentTimeLineListRes{}

// UnibeeApiMerchantPaymentTimeLineListRes struct for UnibeeApiMerchantPaymentTimeLineListRes
type UnibeeApiMerchantPaymentTimeLineListRes struct {
	// PaymentTimeLines
	PaymentTimeLines []UnibeeInternalModelEntityOverseaPayPaymentTimeline `json:"paymentTimeLines,omitempty"`
}

// NewUnibeeApiMerchantPaymentTimeLineListRes instantiates a new UnibeeApiMerchantPaymentTimeLineListRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnibeeApiMerchantPaymentTimeLineListRes() *UnibeeApiMerchantPaymentTimeLineListRes {
	this := UnibeeApiMerchantPaymentTimeLineListRes{}
	return &this
}

// NewUnibeeApiMerchantPaymentTimeLineListResWithDefaults instantiates a new UnibeeApiMerchantPaymentTimeLineListRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnibeeApiMerchantPaymentTimeLineListResWithDefaults() *UnibeeApiMerchantPaymentTimeLineListRes {
	this := UnibeeApiMerchantPaymentTimeLineListRes{}
	return &this
}

// GetPaymentTimeLines returns the PaymentTimeLines field value if set, zero value otherwise.
func (o *UnibeeApiMerchantPaymentTimeLineListRes) GetPaymentTimeLines() []UnibeeInternalModelEntityOverseaPayPaymentTimeline {
	if o == nil || IsNil(o.PaymentTimeLines) {
		var ret []UnibeeInternalModelEntityOverseaPayPaymentTimeline
		return ret
	}
	return o.PaymentTimeLines
}

// GetPaymentTimeLinesOk returns a tuple with the PaymentTimeLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnibeeApiMerchantPaymentTimeLineListRes) GetPaymentTimeLinesOk() ([]UnibeeInternalModelEntityOverseaPayPaymentTimeline, bool) {
	if o == nil || IsNil(o.PaymentTimeLines) {
		return nil, false
	}
	return o.PaymentTimeLines, true
}

// HasPaymentTimeLines returns a boolean if a field has been set.
func (o *UnibeeApiMerchantPaymentTimeLineListRes) HasPaymentTimeLines() bool {
	if o != nil && !IsNil(o.PaymentTimeLines) {
		return true
	}

	return false
}

// SetPaymentTimeLines gets a reference to the given []UnibeeInternalModelEntityOverseaPayPaymentTimeline and assigns it to the PaymentTimeLines field.
func (o *UnibeeApiMerchantPaymentTimeLineListRes) SetPaymentTimeLines(v []UnibeeInternalModelEntityOverseaPayPaymentTimeline) {
	o.PaymentTimeLines = v
}

func (o UnibeeApiMerchantPaymentTimeLineListRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnibeeApiMerchantPaymentTimeLineListRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PaymentTimeLines) {
		toSerialize["paymentTimeLines"] = o.PaymentTimeLines
	}
	return toSerialize, nil
}

type NullableUnibeeApiMerchantPaymentTimeLineListRes struct {
	value *UnibeeApiMerchantPaymentTimeLineListRes
	isSet bool
}

func (v NullableUnibeeApiMerchantPaymentTimeLineListRes) Get() *UnibeeApiMerchantPaymentTimeLineListRes {
	return v.value
}

func (v *NullableUnibeeApiMerchantPaymentTimeLineListRes) Set(val *UnibeeApiMerchantPaymentTimeLineListRes) {
	v.value = val
	v.isSet = true
}

func (v NullableUnibeeApiMerchantPaymentTimeLineListRes) IsSet() bool {
	return v.isSet
}

func (v *NullableUnibeeApiMerchantPaymentTimeLineListRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnibeeApiMerchantPaymentTimeLineListRes(val *UnibeeApiMerchantPaymentTimeLineListRes) *NullableUnibeeApiMerchantPaymentTimeLineListRes {
	return &NullableUnibeeApiMerchantPaymentTimeLineListRes{value: val, isSet: true}
}

func (v NullableUnibeeApiMerchantPaymentTimeLineListRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnibeeApiMerchantPaymentTimeLineListRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


